---
name: "Suggestion"
about: "Propose a new idea or improvement for this project."
title: "[Suggestion]: "
labels: ["new_issue"]
assignees: []
---

## Suggestion Summary

_Describe your suggestion or idea in a clear and concise way._

## Motivation

_Explain why this suggestion would be beneficial to the project or its users._

## Additional Context

_Add any other context, screenshots, or examples about the suggestion here._
