name: Suggestion
description: Make a suggestion
title: "[Suggestion]: "
labels: ["new_issue","assign"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: Also tell us, how do you suggest accomplishing it?
      placeholder: "Tell us what you'd like to see!"
      value: "A suggestion"
    validations:
      required: true
