
name: Issue Ops Auto Response
permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  auto-respond:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read autoresponse template
        id: read_template
        run: |
          TEMPLATE_PATH=".github/workflows/configurations/autoresponse_template.md"
          RESPONSE=$(cat "$TEMPLATE_PATH")
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post auto-response comment
        uses: actions/github-script@v7
        with:
          script: |
            const response = process.env['RESPONSE'] || "${{ steps.read_template.outputs.response }}";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: response
            });
        env:
          RESPONSE: ${{ steps.read_template.outputs.response }}

      - name: Remove 'new_issue' label
        uses: actions/github-script@v7
        with:
          script: |
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            if (labels.some(label => label.name === 'new_issue')) {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'new_issue'
              });
            }

      - name: Add 'assign' label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['assign']
            });
