
name: 48hr Assignee Reminder
permissions:
  issues: write

on:
  schedule:
    - cron: '0 14 * * *' # Every day at 9am EST (14:00 UTC)

jobs:
  email-assignee-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Find issues awaiting assignee response
        uses: actions/github-script@v7
        id: find_awaiting
        with:
          script: |
            // Helper to calculate business days difference
            function businessDaysBetween(date1, date2) {
              let count = 0;
              let cur = new Date(date1);
              while (cur < date2) {
                const day = cur.getDay();
                if (day !== 0 && day !== 6) count++;
                cur.setDate(cur.getDate() + 1);
              }
              return count;
            }
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            let awaiting = [];
            for (const issue of issues) {
              if (!issue.assignee || issue.pull_request) continue;
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                per_page: 100
              });
              if (!comments.length) continue;
              let lastComment = comments[comments.length - 1];
              let lastResponder = lastComment.user.login;
              let lastUpdated = new Date(lastComment.created_at);
              let now = new Date();
              if (lastResponder !== issue.assignee.login && businessDaysBetween(lastUpdated, now) > 2) {
                awaiting.push({
                  number: issue.number,
                  assignee: issue.assignee.login
                });
              }
            }
            core.setOutput('awaiting', JSON.stringify(awaiting));

      - name: Comment and @mention assignees
        if: steps.find_awaiting.outputs.awaiting != '[]'
        uses: actions/github-script@v7
        with:
          script: |
            const awaiting = JSON.parse('${{ steps.find_awaiting.outputs.awaiting }}');
            for (const item of awaiting) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: item.number,
                body: `Hi @${item.assignee}, the user has responded to this issue and is awaiting your reply. Please take a look when you have a moment!`
              });
            }
